# Generated by Django 2.2.11 on 2021-02-08 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookauthor', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='books/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'docx', 'odt', 'pptx'))])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploadedby', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
