# Generated by Django 3.1.6 on 2021-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='BooksDB',
        ),
    ]
