# Generated by Django 3.1.6 on 2021-02-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_auto_20210209_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
    ]
